vector_db:
  index_name: "school-chatbot"

retriever:
  top_k: 5
  score_threshold: 0.5

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
  google:
    provider: "google"
    model_name: "gemini-1.5-flash"
  openai:
    provider: "openai"
    model_name: "gpt-3.5-turbo"
